// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xukateohrvlleffmvbmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1a2F0ZW9ocnZsbGVmZm12Ym1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNjg0ODEsImV4cCI6MjA2ODc0NDQ4MX0.vNQwHr3Z8q_SXhVUhUEzN4cnIZYGD1cLuHUx9nNI36Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});